// <auto-generated />
using System;
using Engines.DataBaseStorageEngines;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Engines.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    partial class ProjectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Engines.DataBaseStorageEngines.Entities.JsDependencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("JsMetadataId")
                        .HasColumnType("uuid");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JsMetadataId");

                    b.ToTable("js_dependencies", (string)null);
                });

            modelBuilder.Entity("Engines.DataBaseStorageEngines.Entities.JsMetadataRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CriticalVulnerabilities")
                        .HasColumnType("integer");

                    b.Property<int>("DependencyCount")
                        .HasColumnType("integer");

                    b.Property<int>("FileCount")
                        .HasColumnType("integer");

                    b.Property<int>("HighVulnerabilities")
                        .HasColumnType("integer");

                    b.Property<string>("NodeVersion")
                        .HasColumnType("text");

                    b.Property<string>("NpmVersion")
                        .HasColumnType("text");

                    b.Property<long>("PackageSize")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProjectVersion")
                        .HasColumnType("text");

                    b.Property<long>("UnpackedSize")
                        .HasColumnType("bigint");

                    b.Property<int>("VulnerabilityCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("js_project_metadata", (string)null);
                });

            modelBuilder.Entity("Engines.DataBaseStorageEngines.Entities.JsVulnerabilityRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("JsMetadataId")
                        .HasColumnType("uuid");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JsMetadataId");

                    b.ToTable("js_vulnerabilities", (string)null);
                });

            modelBuilder.Entity("Engines.DataBaseStorageEngines.Entities.ProjectRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BucketName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProjectType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StorageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VirusScanResult")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Engines.DataBaseStorageEngines.Entities.RiskAssessmentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("AssessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IssuesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RiskScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("risk_assessments", (string)null);
                });

            modelBuilder.Entity("Engines.DataBaseStorageEngines.Entities.JsDependencyRecord", b =>
                {
                    b.HasOne("Engines.DataBaseStorageEngines.Entities.JsMetadataRecord", "JsMetadata")
                        .WithMany("Dependencies")
                        .HasForeignKey("JsMetadataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JsMetadata");
                });

            modelBuilder.Entity("Engines.DataBaseStorageEngines.Entities.JsVulnerabilityRecord", b =>
                {
                    b.HasOne("Engines.DataBaseStorageEngines.Entities.JsMetadataRecord", "JsMetadata")
                        .WithMany("Vulnerabilities")
                        .HasForeignKey("JsMetadataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JsMetadata");
                });

            modelBuilder.Entity("Engines.DataBaseStorageEngines.Entities.RiskAssessmentRecord", b =>
                {
                    b.HasOne("Engines.DataBaseStorageEngines.Entities.ProjectRecord", "Project")
                        .WithMany("RiskAssessments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Engines.DataBaseStorageEngines.Entities.JsMetadataRecord", b =>
                {
                    b.Navigation("Dependencies");

                    b.Navigation("Vulnerabilities");
                });

            modelBuilder.Entity("Engines.DataBaseStorageEngines.Entities.ProjectRecord", b =>
                {
                    b.Navigation("RiskAssessments");
                });
#pragma warning restore 612, 618
        }
    }
}
