// <auto-generated />
using System;
using Engines.DataBaseStorageEngines;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Engines.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    partial class ProjectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Engines.DataBaseStorageEngines.Entities.ExecutableProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArtifactBucket")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ArtifactName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContainerId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DockerNetworkId")
                        .HasColumnType("text");

                    b.Property<string>("DockerNetworkName")
                        .HasColumnType("text");

                    b.Property<Guid>("SourceProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StorageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VirusScanResult")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SourceProjectId");

                    b.ToTable("executable_projects", (string)null);
                });

            modelBuilder.Entity("Engines.DataBaseStorageEngines.Entities.JsDependencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("JsMetadataId")
                        .HasColumnType("uuid");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JsMetadataId");

                    b.ToTable("js_dependencies", (string)null);
                });

            modelBuilder.Entity("Engines.DataBaseStorageEngines.Entities.JsMetadataRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CriticalVulnerabilities")
                        .HasColumnType("integer");

                    b.Property<int>("DependencyCount")
                        .HasColumnType("integer");

                    b.Property<int>("FileCount")
                        .HasColumnType("integer");

                    b.Property<int>("HighVulnerabilities")
                        .HasColumnType("integer");

                    b.Property<string>("NodeVersion")
                        .HasColumnType("text");

                    b.Property<string>("NpmVersion")
                        .HasColumnType("text");

                    b.Property<long>("PackageSize")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProjectVersion")
                        .HasColumnType("text");

                    b.Property<long>("UnpackedSize")
                        .HasColumnType("bigint");

                    b.Property<int>("VulnerabilityCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("js_project_metadata", (string)null);
                });

            modelBuilder.Entity("Engines.DataBaseStorageEngines.Entities.JsVulnerabilityRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("JsMetadataId")
                        .HasColumnType("uuid");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JsMetadataId");

                    b.ToTable("js_vulnerabilities", (string)null);
                });

            modelBuilder.Entity("Engines.DataBaseStorageEngines.Entities.ProjectRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BucketName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProjectType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StorageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Engines.DataBaseStorageEngines.Entities.RiskAssessmentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("AssessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExecutableProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("IssuesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RiskScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExecutableProjectId");

                    b.ToTable("risk_assessments", (string)null);
                });

            modelBuilder.Entity("Engines.DataBaseStorageEngines.Entities.ExecutableProject", b =>
                {
                    b.HasOne("Engines.DataBaseStorageEngines.Entities.ProjectRecord", "SourceProject")
                        .WithMany("ExecutableProjects")
                        .HasForeignKey("SourceProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceProject");
                });

            modelBuilder.Entity("Engines.DataBaseStorageEngines.Entities.JsDependencyRecord", b =>
                {
                    b.HasOne("Engines.DataBaseStorageEngines.Entities.JsMetadataRecord", "JsMetadata")
                        .WithMany("Dependencies")
                        .HasForeignKey("JsMetadataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JsMetadata");
                });

            modelBuilder.Entity("Engines.DataBaseStorageEngines.Entities.JsMetadataRecord", b =>
                {
                    b.HasOne("Engines.DataBaseStorageEngines.Entities.ExecutableProject", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Engines.DataBaseStorageEngines.Entities.JsVulnerabilityRecord", b =>
                {
                    b.HasOne("Engines.DataBaseStorageEngines.Entities.JsMetadataRecord", "JsMetadata")
                        .WithMany("Vulnerabilities")
                        .HasForeignKey("JsMetadataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JsMetadata");
                });

            modelBuilder.Entity("Engines.DataBaseStorageEngines.Entities.RiskAssessmentRecord", b =>
                {
                    b.HasOne("Engines.DataBaseStorageEngines.Entities.ExecutableProject", "ExecutableProject")
                        .WithMany("RiskAssessments")
                        .HasForeignKey("ExecutableProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExecutableProject");
                });

            modelBuilder.Entity("Engines.DataBaseStorageEngines.Entities.ExecutableProject", b =>
                {
                    b.Navigation("RiskAssessments");
                });

            modelBuilder.Entity("Engines.DataBaseStorageEngines.Entities.JsMetadataRecord", b =>
                {
                    b.Navigation("Dependencies");

                    b.Navigation("Vulnerabilities");
                });

            modelBuilder.Entity("Engines.DataBaseStorageEngines.Entities.ProjectRecord", b =>
                {
                    b.Navigation("ExecutableProjects");
                });

            modelBuilder.Entity("Engines.DataBaseStorageEngines.Entities.AgentRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy",
                            NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DockerHost")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hostname")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AgentId")
                        .IsUnique();

                    b.ToTable("agent_records", (string)null);
                });

            modelBuilder.Entity("Engines.DataBaseStorageEngines.Entities.EditorSessionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy",
                            NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContainerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkspaceVolume")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NpmCacheVolume")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContainerIp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AgentId")
                        .HasColumnType("text");

                    b.Property<string>("ContainerId")
                        .HasColumnType("text");

                    b.Property<int?>("NetworkRecordId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.HasIndex("NetworkRecordId");

                    b.ToTable("editor_sessions", (string)null);
                });

            modelBuilder.Entity("Engines.DataBaseStorageEngines.Entities.ProjectNetworkRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy",
                            NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NetworkDockerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NetworkName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastActivity")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("project_networks", (string)null);
                });

            modelBuilder.Entity("Engines.DataBaseStorageEngines.Entities.ProjectResourceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy",
                            NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NetworkRecordId")
                        .HasColumnType("integer");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContainerDockerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContainerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageTag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EnvironmentJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastHealthCheck")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("NetworkRecordId");

                    b.ToTable("project_resources", (string)null);
                });

            modelBuilder.Entity("Engines.DataBaseStorageEngines.Entities.EditorSessionRecord", b =>
                {
                    b.HasOne("Engines.DataBaseStorageEngines.Entities.ProjectNetworkRecord", "NetworkRecord")
                        .WithMany("EditorSessions")
                        .HasForeignKey("NetworkRecordId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NetworkRecord");
                });

            modelBuilder.Entity("Engines.DataBaseStorageEngines.Entities.ProjectResourceRecord", b =>
                {
                    b.HasOne("Engines.DataBaseStorageEngines.Entities.ProjectNetworkRecord", "NetworkRecord")
                        .WithMany("Resources")
                        .HasForeignKey("NetworkRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NetworkRecord");
                });

            modelBuilder.Entity("Engines.DataBaseStorageEngines.Entities.ProjectNetworkRecord", b =>
                {
                    b.Navigation("Resources");

                    b.Navigation("EditorSessions");
                });

#pragma warning restore 612, 618
        }
    }
}
