using Engines.DataBaseStorageEngines;
using Engines.DataBaseStorageEngines.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Minio;
using Minio.DataModel.Args;
using System.Text;

namespace Engines.FileStorageEngines.Resources;

public class SdkInjectionService
{
    private readonly ProjectDbContext _db;
    private readonly IConfiguration _config;

    // Credentials are identical across all MinIO instances in this setup.
    // Endpoint and bucket are resolved per-project from ProjectRecord (see GetMinioClientForProjectAsync).
    private string MinioAccessKey => _config["EditorContainer:MinioAccessKey"] ?? "minioadmin";
    private string MinioSecretKey => _config["EditorContainer:MinioSecretKey"] ?? "minioadmin";

    public SdkInjectionService(ProjectDbContext db, IConfiguration config)
    {
        _db     = db;
        _config = config;
    }

    // ── GetMinioClientForProjectAsync ───────────────────────────────────────
    // Resolves the correct MinIO client and bucket for a project by reading
    // ProjectRecord.StorageUrl and ProjectRecord.BucketName from the DB.
    // This mirrors the BFF's clientForProject(projectId) pattern in minioClient.js:
    //   projectServerMap[projectId] → "host:port" derived from ProjectRecord.StorageUrl.
    // Ensures the SDK file is always written to the same MinIO instance that
    // hosts the project's editor workspace — regardless of current election state.

    private async Task<(IMinioClient client, string bucket)> GetMinioClientForProjectAsync(string projectId)
    {
        var project = await _db.Projects.FirstOrDefaultAsync(p => p.Id == Guid.Parse(projectId))
            ?? throw new InvalidOperationException($"Project '{projectId}' not found — cannot resolve MinIO endpoint.");

        var uri    = new Uri(project.StorageUrl);   // e.g. "http://127.0.0.1:9002"
        var client = new MinioClient()
            .WithEndpoint(uri.Host, uri.Port)
            .WithCredentials(MinioAccessKey, MinioSecretKey)
            .WithSSL(false)
            .Build();

        return (client, project.BucketName);
    }

    // ── InjectHelperAsync ───────────────────────────────────────────────────
    // Writes the SDK helper file directly to MinIO at {projectId}/{fileName}.
    // The editor container's rclone FUSE mount surfaces this as /workspace/{fileName}.
    // agentId is not needed — MinIO writes are direct HTTP, no Docker required.

    public async Task InjectHelperAsync(string projectId, ResourceType resourceType)
    {
        var definition = ResourceCatalog.GetDefinition(resourceType);
        if (definition.HelperSdkFileName is null) return;

        var contentBytes        = Encoding.UTF8.GetBytes(GetHelperContent(resourceType));
        var (client, bucket)    = await GetMinioClientForProjectAsync(projectId);

        using var stream = new MemoryStream(contentBytes);
        await client.PutObjectAsync(new PutObjectArgs()
            .WithBucket(bucket)
            .WithObject($"{projectId}/{definition.HelperSdkFileName}")
            .WithStreamData(stream)
            .WithObjectSize(contentBytes.Length)
            .WithContentType("application/javascript"));

        Console.WriteLine(
            $"[sdk-injection] Wrote {definition.HelperSdkFileName} → MinIO {bucket}/{projectId}/");
    }

    // ── WriteResourceEnvFileAsync ───────────────────────────────────────────
    // Writes a .env.resources file to MinIO reflecting ALL currently active
    // resources for the project. Overwrites the file completely on each call
    // so it stays in sync as resources are added over time.
    // The file appears as /workspace/.env.resources in the editor container.

    public async Task WriteResourceEnvFileAsync(string projectId)
    {
        var activeResources = await _db.ProjectResources
            .Where(r => r.ProjectId == projectId && r.Status != "Stopped")
            .ToListAsync();

        var sb = new StringBuilder();
        sb.AppendLine("# Auto-generated by ContainerManager — resource connection details");
        sb.AppendLine("# Usage in your app: require('dotenv').config({ path: '.env.resources' })");

        foreach (var resource in activeResources)
        {
            if (!Enum.TryParse<ResourceType>(resource.ResourceType, out var resType)) continue;

            var definition = ResourceCatalog.GetDefinition(resType);
            sb.AppendLine();
            sb.AppendLine($"# {definition.DisplayName}");
            sb.AppendLine($"{definition.EnvVarPrefix}_HOST={definition.DefaultAlias}");
            sb.AppendLine($"{definition.EnvVarPrefix}_PORT={definition.DefaultPort}");

            foreach (var kv in definition.ContainerEnvVars)
                sb.AppendLine($"{definition.EnvVarPrefix}_{kv.Key}={kv.Value}");
        }

        var contentBytes     = Encoding.UTF8.GetBytes(sb.ToString());
        var (client, bucket) = await GetMinioClientForProjectAsync(projectId);

        using var stream = new MemoryStream(contentBytes);
        await client.PutObjectAsync(new PutObjectArgs()
            .WithBucket(bucket)
            .WithObject($"{projectId}/.env.resources")
            .WithStreamData(stream)
            .WithObjectSize(contentBytes.Length)
            .WithContentType("text/plain"));

        Console.WriteLine(
            $"[sdk-injection] Wrote .env.resources ({activeResources.Count} resources) → MinIO {bucket}/{projectId}/");
    }

    // ── GetHelperContent ────────────────────────────────────────────────────

    public string GetHelperContent(ResourceType resourceType) => resourceType switch
    {
        ResourceType.MySQL => @"// Auto-generated by ContainerManager — MySQL resource helper
const mysql = require('mysql2/promise');
const pool = mysql.createPool({
  host: process.env.DB_HOST || 'db',
  port: parseInt(process.env.DB_PORT || '3306'),
  user: 'root',
  password: process.env.DB_PASSWORD || 'dev-secret',
  database: process.env.DB_NAME || 'app',
  waitForConnections: true,
  connectionLimit: 10,
});
module.exports = pool;
",
        ResourceType.Redis => @"// Auto-generated by ContainerManager — Redis resource helper
const Redis = require('ioredis');
const client = new Redis({
  host: process.env.REDIS_HOST || 'cache',
  port: parseInt(process.env.REDIS_PORT || '6379'),
});
module.exports = client;
",
        ResourceType.MongoDB => @"// Auto-generated by ContainerManager — MongoDB resource helper
const { MongoClient } = require('mongodb');
const url = `mongodb://${process.env.MONGO_HOST || 'mongo'}:${process.env.MONGO_PORT || '27017'}`;
const client = new MongoClient(url);
module.exports = { client, db: () => client.db(process.env.MONGO_DB || 'app') };
",
        ResourceType.PostgreSQL => @"// Auto-generated by ContainerManager — PostgreSQL resource helper
const { Pool } = require('pg');
const pool = new Pool({
  host: process.env.PG_HOST || 'pg',
  port: parseInt(process.env.PG_PORT || '5432'),
  user: 'postgres',
  password: process.env.PG_PASSWORD || 'dev-secret',
  database: process.env.PG_DB || 'app',
});
module.exports = pool;
",
        _ => throw new ArgumentOutOfRangeException(nameof(resourceType)),
    };
}
